# Generated by Django 3.2.9 on 2022-02-11 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enzyme', models.CharField(max_length=200)),
                ('enzymeAbbr', models.CharField(default='ENZYME', max_length=8)),
                ('reversible', models.CharField(max_length=200)),
                ('xCoor', models.IntegerField(default=0)),
                ('yCoor', models.IntegerField(default=0)),
                ('enzWeight', models.IntegerField(default=1)),
                ('deltaG', models.FloatField(default=-1.0)),
                ('deltaGNaughtPrime', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Substrates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substrate', models.CharField(max_length=200)),
                ('abbr', models.CharField(default='SUB', max_length=8)),
                ('modelID', models.IntegerField(default=1)),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biopath.module')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('abbr', models.CharField(default='PROD', max_length=8)),
                ('modelID', models.IntegerField(default=1)),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biopath.module')),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=200)),
                ('public', models.BooleanField(default=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='modelID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biopath.pathway'),
        ),
    ]
