# Generated by Django 3.2.9 on 2022-02-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biopath', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathway',
            name='userID',
        ),
    ]
