# Generated by Django 4.0.2 on 2022-02-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biopath', '0003_auto_20220216_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cofactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cofactor', models.CharField(max_length=200)),
                ('cofactorAbbr', models.CharField(max_length=200)),
                ('modelID', models.IntegerField(default=1)),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biopath.module')),
            ],
        ),
    ]
